# Client App before: node:8.10.0
FROM node:8.10.0 as client-app
LABEL authors="Eprel"
RUN npm install --quiet --no-progress -g @angular/cli@1.7.2
# OR TRY: RUN npm install -g @angular/cli --unsafe --silent
# RUN npm -g config set user root
WORKDIR /usr/src/app
COPY ["package.json", "package-lock.json", "./"]
RUN npm install --quiet
COPY . .
RUN ng build --prod --build-optimizer
RUN npm cache clean --force

# Node server
FROM node:8.10.0 as node-server
WORKDIR /usr/src/app
COPY ["./src/server/package.json", "./src/server/package-lock.json", "./"]
RUN npm install --production --silent && mv node_modules ../
# RUN npm install --production --quiet
COPY ./src/server /usr/src/app

# Final image
FROM node:8.10.0
WORKDIR /usr/src/app
COPY --from=node-server /usr/src /usr/src
# COPY --from=node-server /usr/src/app /usr/src/app
COPY --from=client-app /usr/src/app/dist ./
EXPOSE 3000
CMD ["node", "index"]