version: "3.3"

services:
  ng_toh_az_ssi_secret_docker_compose:
    image: iameprel/ng_toh_az_ssi_secret_docker_compose:1.1
    user: root
    working_dir: /usr/src/app
    secrets:
      - DB_HOST
      - DB_NAME
      - DB_USER_NAME
      - DB_PASSWORD
      - JWT_SECRET
    build: .
    ports:
      - 4000:3000
secrets:
  DB_HOST:
    file: ./secrets/DB_HOST
  DB_NAME:
    file: ./secrets/DB_NAME
  DB_USER_NAME:
    file: ./secrets/DB_USER_NAME
  DB_PASSWORD:
    file: ./secrets/DB_PASSWORD
  JWT_SECRET:
    file: ./secrets/JWT_SECRET
