version: "3.3"

services:
  secret-simulator:
    image: mikesir87/secrets-simulator
    volumes:
      - secrets:/run/secrets:rw
    environment:
      JWT_SECRET: your-jwt-secret
      DB_MODE: your-db-mode
      DB_HOST: your-host-ip
      DB_NAME: your-database-name
      DB_USER_NAME: your-db-user-name
      DB_PASSWORD: your-db-password
  ng_toh_az_ssi_secret_simulator:
    image: iameprel/ng_toh_az_ssi_secret_simulator:1.1
    user: root
    working_dir: /usr/src/app
    volumes:
      - secrets:/run/secrets:ro
    build: .
    ports:
      - 4000:3000

volumes:
  secrets:
    driver: local
