version: "3.3"

services:
  mongo:
    image: mongo
    container_name: mongo
    environment:
      - MONGO_LOG_DIR=/dev/null
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=userintranewuserpass
    volumes:
      - /data/db:/data/db
      # if you wish to setup additional user accounts specific per DB or with different roles you can use following entry point
      # just create docker-entrypoint.sh file and follow the instructions online
      # - ./mongo-entrypoint/:/docker-entrypoint-initdb.d/
    ports:
      - 27017:27017
    command: mongod --auth --smallfiles --port 27017 --dbpath /data/db --logpath=/dev/null --quiet
  ngtohssimongo:
    image: iameprel/ngtohssimongo:1.0.0
    user: root
    working_dir: /usr/src/app
    volumes:
      - ./secrets:/run/secrets
    build: .
    ports:
      - 4000:3000
    links:
      - mongo:mongo
    depends_on:
      - mongo

