version: "3.3"

services:
  ng_toh_az_ssi_manual_secret_mount:
    image: iameprel/ng_toh_az_ssi_manual_secret_mount:1.1
    user: root
    working_dir: /usr/src/app
    volumes:
      - ./secrets:/run/secrets
    build: .
    ports:
      - 4000:3000
