version: '3.3'

services:
  ng_toh_az_ssi_development:
    image: iameprel/prefixes:0.1.0
    user: root
    working_dir: /usr/src/app
    build: .
    env_file: env_file
    environment:
      NODE_ENV: development
    ports:
      - 3001:3001
      - 9229:9229
    command: node --inspect=0.0.0.0:9229 index.js
