apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: prefixes
spec:
  selector:
    matchLabels:
      app: prefixes
      version: v1
      tier: frontend
  replicas: 2
  template:
    metadata:
      labels:
        app: prefixes
        version: v1
        tier: frontend
    spec:
      containers:
        - name: prefixes
          image: iameprel/prefixes-kube:0.0.10
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          env:
          - name: DB_HOST
            value: mongo-db-ip
          - name: DB_MODE
            value: PRODUCTION
          - name: DB_NAME
            value: db-name
          - name: DB_USER_NAME
            value: db-user-name
          - name: DB_PASSWORD
            value: db-password
          - name: JWT_SECRET
            value: jwt-secret
          - name: TWILIO_ACCOUNT_SID
            value: twilio-account-sid
          - name: TWILIO_AUTH_TOKEN
            value: twilio-auth-token
          - name: TWILIO_FROM_NUMBER
            value: "twilio-from-number"
          ports:
          - containerPort: 3000